name: Maven jar

on: 
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B -DskipTests deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
